services:
  kafka-controller-1:
    image: apache/kafka:3.8.1
    container_name: kafka-controller-1
    volumes:
      - controller_data_1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLE: controller-1
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT ###none security 
      ##can use another method : 
      # SSL/TLS: Mã hóa dữ liệua
      # SASL: Hỗ trợ xác thực
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka_spark_net

  kafka-controller-2:
    image: apache/kafka:3.8.1
    container_name: kafka-controller-2
    volumes:
      - controller_data_2:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLE: controller-2
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093 , 2@kafka-controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka_spark_net

  kafka-controller-3:
    image: apache/kafka:3.8.1
    container_name: kafka-controller-3
    volumes:
      - controller_data_3:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLE: controller-3
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093 ,2@kafka-controller-2:9093 , 3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - kafka_spark_net

  kafka-broker-1:
    image: apache/kafka:3.8.1
    container_name: kafka-broker-1
    volumes:
      - broker_data_1:/var/lib/kafka/data
    ports:
      - "29092:9092"
    
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_PROCESS_ROLE: broker-1
      KAFKA_LISTENERS: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-1:19092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093 #,2@kafka-controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - kafka_spark_net

  kafka-broker-2:
    image: apache/kafka:3.8.1
    container_name: kafka-broker-2
    volumes:
      - broker_data_2:/var/lib/kafka/data
    ports:
      - "29092:9092"
    
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_PROCESS_ROLE: broker-2
      KAFKA_LISTENERS: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-2:19092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093 ,2@kafka-controller:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - kafka_spark_net
    
  kafka-broker-3:
    image: apache/kafka:3.8.1
    container_name: kafka-broker-3
    volumes:
      - broker_data_3:/var/lib/kafka/data
    ports:
      - "29092:9092"
    
    environment:
      KAFKA_BROKER_ID: 6
      KAFKA_PROCESS_ROLE: broker-6
      KAFKA_LISTENERS: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-3:19092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENERS_NAME: CONTROLLER
      KAFKA_LISTENERS_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093 ,2@kafka-controller:9093 , 3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - kafka_spark_net

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - "18081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-broker-1:19092
      SCHEMA_REGISTRY_KAKFASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081
    networks:
      - kafka_spark_net
  
  console:
    image: docker.redpanda.com/redpandadata/console:v2.5.2
    entrypoint: /bin/sh 
    command: |-
      -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.json; /app/console'
    ports:
      -8080:8080
    depends_on:
      - schema-registry
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: >
        kafka:
          broker: ["kafka-broker-1:19092"," kafka-broker-2:19092", "kafka-broker-3:19092"]
          schema_registry: 
            enable: true
            urls: ["http://schema-registry:18081"]
        
        redpanda:
          adminAPI:
            enable: false
            urls: ["http://kafka_broker:9644"]
          connect:
            enable: false
            clusters:
              - name: local-connect-cluster
                urls: http://connect:8083
      networks:
        - kafka_spark_net
            


    

networks:
  kafka_spark_net:
    driver: bridge
